### ISSUE TITLE
[Bug] TypeError: run() got an unexpected keyword argument 'on_save'

### ISSUE THREAD

**Issue by Kristinita** [eddiejessup/Transcrypt#8]
### Summary

`Encrypt on save` mode not worked for me. I get stack trace.

### Expected behavior

Encrypt on save.

### Actual behavior

```python
command: transcrypt_toggle_on_save {"on_save": true}
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 795, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'on_save'
```

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install Transcrypt → I restart Sublime Text → I create file with secret information → <kbd>Ctrl+Shift+P</kbd> → `Transcrypt::Enable On Save` → I get stack trace and text not encrypt for me.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
@eddiejessup , reason, why issue closed without any comments?

Thanks.

**Comment by eddiejessup** [comment]
Hey @Kristinita, I closed it because I think I fixed the bug, and even if the same bug appeared superficially, I've changed enough of the implementation that it would be for a different reason than caused the bug in your case. But feel free to try again and see if it now works.

Since I've no easy way to test the plugin on Windows, I might just have to drop support for it.

Sorry for not providing this explanation, I assumed that because the issue was pretty old you'd lost interest :)
